name: CI to build and upload to S3
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        name: install and build
        steps:
            - uses: actions/checkout@v2
              name: Check out repository
            - uses: actions/setup-node@v1
              name: Set up Node.js
              with:
                  node-version: 14
            - run: |
                  yarn install
                  yarn build
    push:
        needs: build
        runs-on: ubuntu-latest
        name: push to S3
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - run: |
                  aws s3 sync dist/ s3://${{secrets.AWS_S3_BUCKET_NAME}} --delete
